export const ADD_TOPPING = 'ADD_TOPPING';
export const UPDATE_SIZE = 'UPDATE_SIZE';
export const UPDATE_TEMP_COUNT = 'UPDATE_TEMP_COUNT';
export const EAT_AT_SHOP = 'EAT_AT_SHOP';
export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';